name: Build Test PR v1

on:
  pull_request:
    branches: [ "v1" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 21, 25 ]

    steps:
      - uses: actions/checkout@v6
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
          cache: maven
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
